### ISSUE TITLE
CL_VERSION definitions do not match documentation

### ISSUE THREAD

**Issue by arghdos** [KhronosGroup/OpenCL-Headers#23]
Hi,
The [documentation](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/preprocessorDirectives.html) lists the CL_VERSION_X_Y preprocessor defines as corresponding to the integer XY0, but all the examples I can find in cl.h for various versions in this repo define it as 1, e.g. [in the 2.2 headers](https://github.com/KhronosGroup/OpenCL-Headers/blob/3dad3346d7643818f342805c249edf3fe9dee2e4/opencl22/CL/cl.h#L203)

Am I missing something?

**Comment by bashbaug** [comment]
This is confusing but I think it is correct, or at least, that it's not necessarily wrong.  The confusion is because there are actually two different `CL_VERSION_X_Y` preprocessor defines:

* The ones in this repo, which contains headers for OpenCL host APIs.  So, these are defines that your host code sees.
* The ones described in the spec, which are preprocessor defines for the OpenCL C programming language.  So, these are defines that your device code sees.

The OpenCL C language spec says clearly that the `CL_VERSION_X_Y` defines on the device side should have specific values, but it doesn't say anything about preprocessor defines on the host side.  Other than avoiding confusion, is there value in changing the host side headers to be consistent, given that there is no `__OPENCL_VERSION__` (or `__OPENCL_C_VERSION__`) on the host side?

**Comment by arghdos** [comment]
@bashbaug Ahhh that explains it.

As for my use case, I was trying to switch between a `clEnqueueFillBuffer` and a `clEnqueueWriteBuffer` for memory initialization on the device side, depending on the result of `getDeviceInfo(...CL_DEVICE_VERSION...)`

It's not strictly necessary but potentially useful I think

**Comment by jrprice** [comment]
> As for my use case, I was trying to switch between a clEnqueueFillBuffer and a clEnqueueWriteBuffer for device memory initialization on the host side, depending on a preprocessor define

This can be achieved with `#ifdef`:

    #ifdef CL_VERSION_1_2
      clEnqueueFillBuffer(...);
    #else
      clEnqueueWriteBuffer(...);
    #endif

This compile-time decision isn't particularly robust though, since these preprocessor definitions give no indication as to what version of the specification the device you run on actually supports. If you wanted to make a decision at runtime, you'd need to use `clGetDeviceInfo(..., CL_DEVICE_VERSION, ...)`, which returns a string representation of the version. 

If the above query returned a numeric value similar to `__OPENCL_VERSION__`, then giving these preprocessor definitions specific values to enable comparisons would be useful, but as it stands I can't see any added value of doing so now (and it's possible that changing the values from `1` to something else would break existing code).

**Comment by arghdos** [comment]
@jrprice 

The way I had been trying to use it is as:

```
#if CL_LEVEL >= CL_VERSION_1_2
   clEnqueueFillBuffer(...);
#else
   clEnqueueWriteBuffer(...);
#endif
```

With `-DCL_LEVEL=110` or the like passed to gcc during the compilation step (fwiw, I pull the device version before compilation via `pyopencl`).  The key being that I'd ideally like to enable the `fillBuffer` for all versions 1.2 and over.  

That said, it's hardly a big issue (I can just internally use the 100, 110, 120, etc.) in my macros.  If it might break anything then it's probably not worth changing
