### ISSUE TITLE
cl_nv_d3d11_sharing header

### ISSUE THREAD

**Issue by emphasis87** [KhronosGroup/OpenCL-Headers#54]
Hi,

where can I find a header for cl_nv_d3d11_sharing and why isn't it included here?

**Comment by bashbaug** [comment]
Hello @emphasis87, since `cl_nv_d3d11_sharing` is a vendor extension it is up to the vendor to define the header for their extension.  I don't work for this vendor, but I do see a header for this extension in their SDK in the file `cl_d3d11_ext.h` - this might work for you?

Note that this functionality was promoted to the multi-vendor KHR extension `cl_khr_d3d11_sharing`, which does have a header file in this repo, if that is an option for you.

**Comment by Squall-Leonhart** [comment]
it might have been promoted into a khr extension, however nvidia has no support for that KHR extension in their OpenCL implementation.

So if you got here because CL_INVALID_VALUE was returned by clCreateContext on nvidia chips while trying to use interop, theres your reason.

**Comment by nikhiljnv** [comment]
Apologize for late response. 
The header for NVIDIA vendor extension cl_nv_d3d11_sharing, cl_d3d11_ext.h, can be found as part of CUDA toolkit or OpenCL SDK. The corresponding Khronos extension cl_khr_d3d11_sharing is not advertised on NVIDIA OpenCL platforms/devices, although cl_nv_d3d11_sharing should have most of the functionality provided by cl_khr_d3d11_sharing.

**Comment by nikhiljnv** [comment]
@bashbaug , I think we can close this issue. 
@emphasis87, any concerns? I suggest to file a bug with NVIDIA if you find any issues wrt this.

**Comment by nikhiljnv** [comment]
@bashbaug , I think we can close this issue. 
@emphasis87, any concerns? I suggest to file a bug with NVIDIA if you find any issues wrt this.

**Comment by nikhiljnv** [comment]
Closing based on my earlier comment as there is no change required in OpenCL headers and required headers for vendor extension should be available from respective vendor SW releases.
