### ISSUE TITLE
Provide releases

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-Headers#56]
We're not currently providing releases of the headers. This makes a number of things like integrating them into Linux distributions a bit challenging. It seems we got a request in the past that was closed without replying or providing a solution (#11). (cc @ghisvail, @vdanjean).

I suggest we use a date-based tagging scheme (e.g. YYYY-MM) to avoid the confusion with OpenCL versions.

**Comment by jrprice** [comment]
I've re-opened #11 - it was wrongly closed automatically due to a commit message with a "Closes #" statement that referenced an unrelated GitLab issue number. I've brought this up in the past, but we really need to stop putting these sorts of things in commit messages to avoid this sort of issue, otherwise this will keep happening.

Agree that a date-based tagging scheme is best since we essentially have a rolling-release process. Releasing at most once per month seems like a sensible frequency.

**Comment by kpet** [comment]
As agreed on the OpenCL Working Group call 2020/01/07, the headers will use a date-based versioning (YYYY-MM-DD).

**Comment by kloczek** [comment]
> As agreed on the OpenCL Working Group call 2020/01/07, the headers will use a date-based versioning (YYYY-MM-DD).

If it would be date version patter please use YYYY.MM.DD as using `-` is forbiden to use in version string by all packaging software.

**Comment by kpet** [comment]
I've now made the first release, using dots as separators as suggested by @kloczek. I'll close this. If anyone needs a release before we make another one, please create an issue.

**Comment by kloczek** [comment]
/me is bowing 

Thank you :)
