### ISSUE TITLE
CL_CONTEXT_TERMINATED_KHR is undefined

### ISSUE THREAD

**Issue by Kerilk** [KhronosGroup/OpenCL-Headers#69]
The CL_CONTEXT_TERMINATED_KHR error code is not defined in any header file.

**Comment by bashbaug** [comment]
Interesting, the `CL_CONTEXT_TERMINATED_KHR` error code is not in the XML file either.

Our options would seem to be:

1. Add the error code to the XML file and headers.
1. Change the spec to use an existing error code instead.
1. Do nothing and leave the error code value undefined until a vendor implements this extension.

Since (1) is straightforward I think we should just add this missing error code.
